Repository COS301-SE-2024/GameOnConnect, pull requests merged in 2024-05, with the labels that each got.

#28 Added upload of coverage
  .github/workflows/flutter.yml
  pubspec.lock
  pubspec.yaml
Labels: backend, CI/CD

#33 Merging Dev to main so that we can see if the badges work.
  .github/workflows/flutter.yml
  README.md
  pubspec.lock
  pubspec.yaml
Labels: backend, CI/CD

#47 Feat/authentication1 into Develop
  lib/main.dart
  lib/pages/home_page.dart
  lib/pages/login_page.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: backend, frontend

#61 Feat/profile page
  lib/main.dart
  lib/pages/home_page.dart
  lib/pages/profile_page.dart
Labels: frontend

#65 Feat/edit profile
  lib/main.dart
  lib/pages/edit_profile_page.dart
  lib/pages/home_page.dart
  test/edit_profile_page_test.dart
Labels: frontend, Testing

#72 Feat/themes into Develop
  lib/main.dart
  lib/pages/customize_page.dart
  lib/theme/theme_provider.dart
  lib/theme/themes.dart
  pubspec.lock
  pubspec.yaml
Labels: backend
