Repository COS301-SE-2024/GameOnConnect, pull requests merged in 2024-09, with the labels that each got.

#514 Fix/usability fixes2 into Develop
  lib/main.dart
  lib/view/components/home/connection_update.dart
  lib/view/components/home/connection_updates.dart
  lib/view/components/home/event_invite.dart
  lib/view/components/home/event_invite_list.dart
  lib/view/components/home/online_friends_list.dart
  lib/view/components/home/start_timer.dart
  lib/view/components/messaging/user_tile.dart
  lib/view/components/profile/activity_card.dart
  lib/view/components/profile/custom_timeline_tile.dart
  lib/view/pages/authentication/login_page.dart
  lib/view/pages/authentication/sign_up_page.dart
  lib/view/pages/game_library/game_details_page.dart
  lib/view/pages/home/home_page.dart
  lib/view/pages/home/welcome_splash.dart
  lib/view/pages/messaging/messaging_page.dart
  lib/view/pages/profile/connections_request_list.dart
  lib/view/pages/profile/game_activity.dart
  lib/view/pages/profile/profile_page.dart
  lib/view/pages/settings/appearance.dart
  lib/view/pages/settings/customize_page.dart
  lib/view/pages/settings/settings_page.dart
Labels: bug, enhancement

#536 Fix/messagesnotloading into Develop
  lib/services/messaging_S/messaging_service.dart
  lib/view/pages/messaging/chat_page.dart
Labels: bug

#533 Fix game library filter
  lib/cache_managers/customize_profile_cache_manager.dart
  lib/cache_managers/filtering_cache_manager.dart
  lib/model/game_library_M/game_filters_model.dart
  lib/services/game_library_S/game_filter_service.dart
  lib/services/game_library_S/game_service.dart
  lib/services/settings/customize_service.dart
  lib/view/components/game_library/game_library_filter.dart
  lib/view/components/search/search_field.dart
  lib/view/pages/events/view_events_page.dart
  lib/view/pages/game_library/game_library_page.dart
Labels: bug, frontend

#595 Fix/bugsandimprovements
  assets/tiles/GameyCon.tiled-session
  assets/tiles/Level-1.tmx
  assets/tiles/Level-2.tmx
  assets/tiles/Level-3.tmx
  lib/view/components/GameyCon/components/background_tile.dart
  lib/view/components/GameyCon/components/checkpoint.dart
  lib/view/components/GameyCon/components/chicken.dart
  lib/view/components/GameyCon/components/collision_block.dart
  lib/view/components/GameyCon/components/custom_hitbox.dart
  lib/view/components/GameyCon/components/fruit.dart
  lib/view/components/GameyCon/components/jump_button.dart
  lib/view/components/GameyCon/components/leavebutton.dart
  lib/view/components/GameyCon/components/levels.dart
  lib/view/components/GameyCon/components/player.dart
  lib/view/components/GameyCon/components/saw.dart
  lib/view/components/GameyCon/components/score.dart
  lib/view/components/GameyCon/components/score_overlay.dart
  lib/view/components/GameyCon/components/tools.dart
  lib/view/components/GameyCon/gameycon_game.dart
  lib/view/components/stats/total_time_boxes.dart
  lib/view/pages/GameyCon/gameycon_page.dart
  lib/view/pages/GameyCon/loadingpage.dart
  lib/view/pages/game_library/game_details_page.dart
Labels: bug, frontend

#598 Fix/bugsandforgotpassword
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/profile/AndroidManifest.xml
  lib/services/authentication_S/auth_service.dart
  lib/view/pages/authentication/login_page.dart
  lib/view/pages/events/create_events_page.dart
  lib/view/pages/settings/customize_page.dart
  lib/view/pages/settings/settings_page.dart
  lib/view/pages/stats/stats_page.dart
  pubspec.lock
  pubspec.yaml
Labels: backend, frontend

#607 added performance to the app
  android/app/build.gradle
  android/settings.gradle
  lib/services/game_library_S/game_service.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, Testing

#614 added messages traces.
  .github/workflows/build.yml
  lib/view/pages/messaging/chat_page.dart
Labels: Testing

#623 Feat/repo enhancement
  README.md
  assets/tiles/GameyCon.tiled-session
  assets/tiles/Level-1.tmx
  assets/tiles/Level-2.tmx
  assets/tiles/Level-3.tmx
  assets/tiles/Level-4.tmx
  assets/tiles/Level-5.tmx
  lib/view/components/GameyCon/gameycon_game.dart
  lib/view/pages/game_library/game_details_page.dart
Labels: frontend
