Repository COS301-SE-2024/GameOnConnect, pull requests merged in 2024-07, with the labels that each got.

#217 feat/loginBugFix2
  lib/services/auth_service.dart
Labels: bug, backend

#249 Feat/messaging page into Develop
  lib/main.dart
  lib/view/pages/authentication/login_page.dart
  lib/view/pages/authentication/sign_up_page.dart
  lib/view/pages/feed/feed_page.dart
  lib/view/pages/messaging/chat_page.dart
  lib/view/pages/messaging/messaging_page.dart
  pubspec.lock
  test/feedpage_test.dart
Labels: backend, frontend

#256 feat/cachingforGameDetails into Develop
  lib/view/components/game_library/carousel_image.dart
  lib/view/components/game_library/game_library_filter.dart
  lib/view/pages/game_library/game_details_page.dart
  lib/view/pages/game_library/game_library_page.dart
Labels: enhancement, frontend

#262 Feat/new user name upon google sign up into Develop
  lib/services/authentication_S/auth_service.dart
  lib/services/profile_S/profile_service.dart
  lib/view/pages/feed/feed_page.dart
  lib/view/pages/game_library/game_details_page.dart
  lib/view/pages/profile/profile_page.dart
  pubspec.lock
  test/feedpage_test.dart
Labels: backend, frontend

#295 Feat/messaging implementation into Develop
  lib/model/messages_M/message_modal.dart
  lib/services/authentication_S/auth_service.dart
  lib/services/messaging_S/messaging_service.dart
  lib/view/components/messaging/chat_bubble_component.dart
  lib/view/components/messaging/user_tile.dart
  lib/view/pages/feed/feed_page.dart
  lib/view/pages/messaging/chat_page.dart
  lib/view/pages/messaging/messaging_page.dart
  pubspec.lock
Labels: backend, frontend, Intergration

#326 Feat/message-cleanup-into-Develop
  lib/services/messaging_S/messaging_service.dart
  lib/view/components/card/connection_list_card.dart
  lib/view/components/messaging/chat_bubble_component.dart
  lib/view/components/messaging/user_tile.dart
  lib/view/pages/feed/feed_page.dart
  lib/view/pages/messaging/messaging_page.dart
Labels: enhancement, backend, frontend

#319 Feat/make create events pretty
  lib/globals.dart
  lib/main.dart
  lib/services/connection_S/connection_service.dart
  lib/services/events_S/event_service.dart
  lib/services/game_library_S/game_service.dart
  lib/view/components/card/connection_list_card.dart
  lib/view/components/card/event_card.dart
  lib/view/components/card/game_list_card.dart
  lib/view/components/card/joined_event_card.dart
  lib/view/pages/events/choose_my_games_page.dart
  lib/view/pages/events/create_events_page.dart
  lib/view/pages/events/invite_connections_page.dart
  lib/view/pages/events/specific_event_details.dart
  lib/view/pages/events/view_events_page.dart
Labels: frontend

#328 feat/logoRework into Develop
  android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  assets/icons/GameOnConnect_Logo_Transparent.png
  assets/icons/GameOnConnect_Logo_Transparent_White.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-50x50@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-50x50@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-57x57@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-57x57@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-72x72@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-72x72@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon-83.5x83.5@2x.png
  lib/view/pages/authentication/login_page.dart
  lib/view/pages/authentication/sign_up_page.dart
  lib/view/pages/events/create_events_page.dart
  lib/view/pages/events/view_events_page.dart
  lib/view/pages/feed/feed_page.dart
  lib/view/pages/profile/profile_page.dart
  lib/view/pages/settings/customize_page.dart
  lib/view/pages/settings/edit_profile_page.dart
  pubspec.yaml
  test/edit_profile_page_test.dart
Labels: enhancement, frontend

#344 Feat/message cleanup2 into Develop
  lib/view/components/appbars/backbutton_appbar_component.dart
  lib/view/components/messaging/chat_bubble_component.dart
  lib/view/components/messaging/user_tile.dart
  lib/view/pages/events/view_events_page.dart
  lib/view/pages/feed/feed_page.dart
  lib/view/pages/messaging/chat_page.dart
  lib/view/pages/messaging/messaging_page.dart
  lib/view/pages/settings/customize_page.dart
  lib/view/pages/settings/edit_profile_page.dart
  lib/view/pages/settings/getting_started_page.dart
  lib/view/pages/settings/help_page.dart
  lib/view/pages/settings/settings_page.dart
  test/getting_started_page_test.dart
  test/settings_test.dart
Labels: enhancement, frontend
