Repository COS301-SE-2024/GameOnConnect, pull requests merged in 2024-08, with the labels that each got.

#365 Fix/defaultprofilecreation
  lib/model/profile_M/profile_model.dart
  lib/services/authentication_S/auth_service.dart
  lib/services/profile_S/profile_service.dart
  lib/view/pages/settings/customize_page.dart
Labels: bug

#388 Fix/message stream into Develop
  lib/services/messaging_S/messaging_service.dart
  lib/view/components/card/connection_list_card.dart
  lib/view/components/messaging/chat_bubble_component.dart
  lib/view/components/messaging/user_tile.dart
  lib/view/pages/messaging/chat_page.dart
  lib/view/pages/messaging/messaging_page.dart
  lib/view/theme/themes.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, backend, frontend

#399 Feat/theme choices into Develop
  lib/main.dart
  lib/view/components/settings/edit_colour_icon_component.dart
  lib/view/pages/settings/customize_page.dart
  lib/view/theme/theme_provider.dart
  lib/view/theme/themes.dart
  pubspec.lock
Labels: frontend

#392 Feat/update view events
  lib/view/components/card/event_card.dart
  lib/view/components/card/joined_event_card.dart
  lib/view/components/event/create_event_chips.dart
  lib/view/components/event/event_card.dart
  lib/view/components/event/joined_event_card.dart
  lib/view/pages/events/create_events_page.dart
  lib/view/pages/events/view_events_page.dart
Labels: frontend

#404 Feat/selectgamepage into Develop
  lib/view/components/card/game_list_card.dart
  lib/view/pages/events/choose_my_games_page.dart
Labels: frontend

#454 Fix/messaging bug fix1 into Develop
  .github/workflows/flutter.yml
  lib/services/authentication_S/auth_service.dart
  lib/services/messaging_S/messaging_service.dart
  lib/view/components/card/connection_list_card.dart
  lib/view/pages/messaging/chat_page.dart
  lib/view/pages/messaging/messaging_page.dart
Labels: bug

#473 Fix/themebugs into Devlop
  lib/main.dart
  lib/view/components/events/specific_events_buttons.dart
  lib/view/components/settings/edit_colour_icon_component.dart
  lib/view/pages/events/create_events_page.dart
  lib/view/pages/settings/customize_page.dart
  lib/view/theme/theme_provider.dart
  lib/view/theme/themes.dart
  pubspec.lock
Labels: bug, frontend

#488 Feat/3d model1 into Develop
  .github/workflows/firebase-hosting-merge.yml.disabled
  .github/workflows/flutter.yml
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/profile/AndroidManifest.xml
  assets/models/mountain_badge.glb
  ios/Runner/Info.plist
  lib/view/components/help/video_widget.dart
  lib/view/components/stats/genres_bar_graph.dart
  lib/view/pages/authentication/login_page.dart
  lib/view/pages/events/view_events_page.dart
  lib/view/pages/feed/feed_page.dart
  lib/view/pages/feed/welcome_splash.dart
  lib/view/pages/models/mountain_badge_page.dart
  lib/view/pages/settings/settings_page.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#502 Feat/message move into profile into Develop
  lib/view/pages/profile/profile_page.dart
Labels: enhancement

#498 Fix/automatically update event details
  lib/model/events_M/events_model.dart
  lib/view/components/events/event_card.dart
  lib/view/components/events/specific_events_buttons.dart
  lib/view/pages/events/choose_my_games_page.dart
  lib/view/pages/events/edit_event_page.dart
  lib/view/pages/events/invite_connections_page.dart
  lib/view/pages/events/specific_event_details.dart
Labels: bug

#505 Fix/usability fixes1 into Develop
  lib/services/settings/customize_service.dart
  lib/view/components/game_library/carousel_image.dart
  lib/view/components/help/contact_us_bottom.dart
  lib/view/components/settings/customize_tag_container.dart
  lib/view/components/settings/edit_colour_icon_component.dart
  lib/view/pages/connections/connections_search_page.dart
  lib/view/pages/feed/feed_page.dart
  lib/view/pages/game_library/game_details_page.dart
  lib/view/pages/messaging/chat_page.dart
  lib/view/pages/profile/profile_page.dart
  lib/view/pages/settings/customize_page.dart
  lib/view/pages/settings/help_page.dart
  lib/view/pages/stats/stats_page.dart
  pubspec.lock
  pubspec.yaml
Labels: frontend
